cevest_almoxarifado/urls.py
from django.urls import path
from . import views

app_name='cevest_almoxarifado'
urlpatterns = [
    path('', views.listar_tipo_materiais, name="index"),
    
    path('getMaterial/<int:id>/', views.getMaterial, name='get_material'),
    path('listar-tipo-materiais/', views.listar_tipo_materiais, name="alm_listar_tipos"),
    path('listar-materiais/', views.listar_materiais, name="alm_listar_materiais"),
    path('adicionar-tipo-materiais/', views.adicionar_tipo_materiais, name="alm_adicionar_tipo"),
    path('adicionar-material/<tipo>', views.adicionar_material, name="alm_adicionar_material"),
    path('adicionar-material-ao-estoque/', views.adicionar_material_ao_estoque, name="alm_adicionar_material_ao_estoque"),
    path('<id>/remover-material-do-estoque/', views.retirar_material_do_estoque, name="alm_remover_material_do_estoque"),
    path('historico/', views.historico, name="historico"),
    
]

cevest_os/urls.py
from django.urls import path
from . import views
 
app_name='cevest_os'
urlpatterns = [
    # path('', views.index, name='os_index'),
    path('', views.os_index, name='os_index'),
    path('painel/', views.os_painel, name='os_painel'),
    path('os/', views.add_os, name='add_os'),

    path('os/painel/<id>/', views.detalhes_os, name='detalhes_os'),
    path('os/painel/<id>/pontos', views.pontos_os, name='pontos_os'),
    path('imprimir/', views.os_index, name='imprimir_nada'),
    path('imprimir/<ids>/', views.imprimir_varias_os, name='imprimir_varias'),
    path('os/painel/<id>/imprimir/', views.imprimir_os, name='imprimir'),
    path('os/painel/<id>/alterar_status/<opcao>', views.change_status_os, name='change_status_os'),
    path('os/painel/<id>/alterar_prioridade/<opcao>', views.change_prioridade_os, name='change_prioridade_os'),
    path('os/painel/<id>/atender', views.atender_os, name='atender_os'),

    path('os/kpi', views.graficos, name='kpi'),
    path('funcionario', views.funcionarios_listar, name='funcionarios'),
    path('funcionario/cadastrar/', views.funcionario_cadastrar, name='cadastrar funcionario'),
    path('funcionario/editar/<id>/', views.funcionario_editar, name='editar funcionario'),
    path('funcionario/deletar/<id>/', views.funcionario_deletar, name='deletar funcionario'),

    path('os/painel/<id>/equipe/', views.atribuir_equipe, name='atribuir equipe')
]

cursos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
 
app_name='cursos'
urlpatterns = [
    path('', views.index, name='home'),
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('editar-cadastro/', views.editar_cadastro, name='editar_cadastro'),
    path('editar-senha/', views.alterar_senha, name='alterar_senha'),
    path('editar-cadastro-pessoa/', views.editar_cadastro_pessoa, name='editar_cadastro_pessoa'),
    path('atividade/<tipo>', views.cursos, name="cursos"),            
    path('atividade/<tipo>/<filtro>', views.cursos_filtrado, name="filtrar"),            
    path('atividade/<tipo>/<id>/detalhe', views.curso_detalhe, name="curso_detalhe"),            
    path('atividade/<tipo>/<id>/matricular', views.matricular, name="matricula"),            
    # path('prematricula/', views.prematricula, name="prematricula"),
    path('ensino-superior/', views.ensino_superior, name="ensino_superior"),
    path('ensino-tecnico/', views.ensino_tecnico, name="ensino_tecnico"),
    path('curriculo-vitae/', views.curriculo_vitae, name="curriculo_vitae"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),    
    path('', include('cursos.urls')),    
    path('eventos/', include('eventos.urls')),    
    path('almoxarifado/', include('cevest_os.urls')),
    path('almoxarifado/a/', include('cevest_almoxarifado.urls')),    
    path('newsletter/', include('newsletter.urls')),

    path('administracao/', include('administracao.urls')),    
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cevest_os/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import CEVEST_OrdemDeServico, Funcionario_CEVEST_OS, CEVEST_OS_ext, CEVEST_OS_Linha_Tempo
from autenticacao.models import Pessoa
from django.contrib.auth.models import Group
from django.forms import ModelChoiceField

class OS_Form(ModelForm):    
    
    class Meta:
        model = CEVEST_OrdemDeServico
        widgets = {
            'tipo': forms.Select(attrs={'readonly': True}),
        }
        exclude = ['numero', 'dt_inclusao', 'atendente', 'dt_conclusao', 'prioridade', 'status', 'contribuinte', 'pontos_atendidos', 'cadastrado_por']


class OS_Form_Ponto(ModelForm):    
    
    class Meta:
        model = CEVEST_OrdemDeServico       
        fields = ['pontos_atendidos']

class PessoaChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.nome
    
class Funcionario_Form(ModelForm):

    pessoa = PessoaChoiceField(queryset=Pessoa.objects.none(), label='Selecione uma pessoa')

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None) or Group.objects.get(name='os_funcionario')
        super().__init__(*args, **kwargs)
        if grupo:
            self.fields['pessoa'].queryset = Pessoa.objects.filter(user__groups=grupo)

    class Meta:
        model = Funcionario_CEVEST_OS
        widgets = {'tipo_os': forms.HiddenInput()}
        fields = ['pessoa', 'nivel', 'tipo_os']

class Funcionario_Form_editar(ModelForm):

    pessoa = PessoaChoiceField(queryset=Pessoa.objects.none(), label='Selecione uma pessoa')

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None) or Group.objects.get(name='os_funcionario')
        super().__init__(*args, **kwargs)
        if grupo:
            self.fields['pessoa'].queryset = Pessoa.objects.filter(user__groups=grupo)

    class Meta:
        model = Funcionario_CEVEST_OS
        widgets = {'tipo_os': forms.HiddenInput()}
        fields = ['pessoa', 'nivel', 'tipo_os']


class Equipe_Form(ModelForm):
    class Meta:
        model = CEVEST_OS_ext
        widgets = {
            'equipe': forms.CheckboxSelectMultiple(),
            'os': forms.HiddenInput()

        }        
        exclude=[]

class NovaMensagemForm(forms.ModelForm):
    class Meta:
        model = CEVEST_OS_Linha_Tempo
        fields = ['os', 'pessoa', 'mensagem', 'anexo']
        widgets = {
            'os': forms.HiddenInput(),
            'pessoa': forms.HiddenInput(),
            'mensagem': forms.Textarea(attrs={'class': 'form-control h-100', 'rows': 6}),
            'anexo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

cevest_os/views.py
from django.shortcuts import render, redirect
from .forms import *
from autenticacao.models import Pessoa
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.apps import apps
from .models import *
from settings.decorators import group_required
from django.contrib.auth.models import Group
from datetime import datetime
from django.db.models import Count, Sum

STATUS_CHOICES=(
        ('0','Novo'),
        ('1','Aguardando'),
        ('2','Em execução'),
        ('f','Finalizado')
    )
PRIORIDADE_CHOICES=(
        ('0','Normal'),
        ('1','Moderada'),
        ('2','Urgente'),
    )

@group_required('cevest_os_acesso')
def index(request):
    return render(request, 'os_index.html')

@login_required
@group_required('cevest_os_acesso')
def os_painel(request):    
    meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    bairros = CEVEST_OrdemDeServico.objects.values_list('bairro', flat=True).distinct()
    data = []
    
    for bairro in bairros:
        total=CEVEST_OrdemDeServico.objects.filter(bairro=bairro, status__in=['0', '1', '2'], dt_solicitacao__year='2023').count()
        os_por_mes =CEVEST_OrdemDeServico.objects.filter(bairro=bairro, status__in=['0', '1', '2'], dt_solicitacao__year='2023').annotate(
            jan=Count('id', filter=models.Q(dt_solicitacao__month=1)),
            fev=Count('id', filter=models.Q(dt_solicitacao__month=2)),
            mar=Count('id', filter=models.Q(dt_solicitacao__month=3)),
            abr=Count('id', filter=models.Q(dt_solicitacao__month=4)),
            mai=Count('id', filter=models.Q(dt_solicitacao__month=5)),
            jun=Count('id', filter=models.Q(dt_solicitacao__month=6)),
            jul=Count('id', filter=models.Q(dt_solicitacao__month=7)),
            ago=Count('id', filter=models.Q(dt_solicitacao__month=8)),
            set=Count('id', filter=models.Q(dt_solicitacao__month=9)),
            out=Count('id', filter=models.Q(dt_solicitacao__month=10)),
            nov=Count('id', filter=models.Q(dt_solicitacao__month=11)),
            dez=Count('id', filter=models.Q(dt_solicitacao__month=12)),
        ).values('jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez')

        data.append({'bairro': bairro, 'mes': os_por_mes, 'total': total})

    
    # if request.method=='POST':
    #     pass

    
    context={
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'data': data,        
    }
    return render(request, 'cevest_os/painel.html', context)

@login_required
@group_required('cevest_os_acesso')
def os_index(request):
    if request.user.is_superuser:
        data=CEVEST_OrdemDeServico.objects.all()
    else:
        data=CEVEST_OrdemDeServico.objects.filter(atendente=Pessoa.objects.get(user=request.user))
    if request.method=='POST':
        valor_da_busca=request.POST['valor_da_busca']
        tipo=request.POST['tipo_da_busca']
        # print(valor_da_busca, tipo)
        if tipo == 'atendente':
            if valor_da_busca=='':
                data=data.filter(atendente=None)
            else:
                data=data.filter(atendente__first_name__icontains=valor_da_busca)
        elif tipo == 'bairro':
            data=data.filter(bairro__icontains=valor_da_busca)
        elif tipo == 'data':
            try:
                valor_da_busca_date = datetime.strptime(valor_da_busca, '%d/%m/%Y').date()            
                data=data.filter(dt_solicitacao__date=valor_da_busca_date.strftime('%Y-%m-%d'))
            except:
                valores=valor_da_busca.split('/')
                # print(valores)
                data=data.filter(dt_solicitacao__year=valores[1], dt_solicitacao__month=valores[0])
        elif tipo == 'protocolo':
            data=data.filter(numero__icontains=valor_da_busca)
        elif tipo == 'rua':
            data=data.filter(logradouro__icontains=valor_da_busca)
        elif tipo == 'status':
            status={'Novo': 0,
            'Aguardando': 1,
            'Em execução': 2,
            'Finalizado': 3}
            data=data.filter(status=status[valor_da_busca.capitalize()])
        elif tipo == 'prioridade':
            prioridades={'Normal': 0,
            'Moderada': 1,
            'Urgente': 2
            }
            data=data.filter(prioridade=prioridades[valor_da_busca.capitalize()])

    paginator = Paginator(data, 30)
    page = request.GET.get('page', 1)
    ordens_de_servico = paginator.get_page(page)
    
    context={
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'ordens_de_servico': ordens_de_servico
    }
    return render(request, 'cevest_os/index.html', context)


@login_required
def add_os(request):
    
    form = OS_Form(initial={'tipo': CEVEST_Tipo_OS.objects.get(sigla='TST').id})

    if request.method=='POST':
        form=OS_Form(request.POST)
        if form.is_valid():
            os=form.save(commit=False)
            os.cadastrado_por=Pessoa.objects.get(user=request.user)
            os.save()

            return redirect('cevest_os:os_index')                

    context={
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'form': form,
    }

    return render(request, 'cevest_os/adicionar_os.html', context)


def detalhes_os(request, id):
    pessoa = Pessoa.objects.get(user=request.user)
    os = CEVEST_OrdemDeServico.objects.get(id=id)
    form_mensagem = NovaMensagemForm(initial={'os': os.id, 'pessoa': pessoa.id})
    try:
        os_ext=CEVEST_OS_ext.objects.get(os=os)        
    except:
        os_ext = None         
    if request.method=='POST': 
        form_mensagem=NovaMensagemForm(request.POST, request.FILES)
        if form_mensagem.is_valid():
           msg=form_mensagem.save(commit=False)
           msg.os=os
           msg.pessoa=pessoa
           msg.save()
           form_mensagem = NovaMensagemForm(initial={'os': os.id, 'pessoa': pessoa.id})       

    linha_tempo=CEVEST_OS_Linha_Tempo.objects.filter(os=os)
    context={
        'form_mensagem': form_mensagem,
        'linha_tempo': linha_tempo,
        'STATUS': STATUS_CHOICES,
        'PRIORIDADES': PRIORIDADE_CHOICES, 
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'os': os,
        'os_ext': os_ext
    }
    return render(request, 'cevest_os/detalhes_os.html', context)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def change_status_os(request, id, opcao):
    os=CEVEST_OrdemDeServico.objects.get(id=id)
    os.status=opcao
    if opcao=='f':
        os.dt_conclusao=datetime.now()
    os.save()
    return redirect('cevest_os:detalhes_os', id=id)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def change_prioridade_os(request, id, opcao):
    os=CEVEST_OrdemDeServico.objects.get(id=id)
    os.prioridade=opcao
    os.save()
    return redirect('cevest_os:detalhes_os', id=id)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def atender_os(request, id):
    os=CEVEST_OrdemDeServico.objects.get(id=id)
    os.atendente=request.user
    os.save()
    return redirect('cevest_os:detalhes_os', id=id)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def funcionarios_listar(request):
    funcionarios=Funcionario_CEVEST_OS.objects.all()
    context={
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'funcionarios': funcionarios
    }
    return render(request, 'equipe/funcionarios.html', context)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def funcionario_cadastrar(request):
    if request.method=='POST':
        form=Funcionario_Form({'pessoa':request.POST['pessoa'], 'nivel': request.POST['nivel'], 'tipo_os': [1]})
        if form.is_valid():
            form.save()
            funcionario=Funcionario_CEVEST_OS()
            return redirect('cevest_os:funcionarios')
        # else:
            # print(form.errors)
    else:
        form=Funcionario_Form(initial={'tipo_os': CEVEST_Tipo_OS.objects.get(sigla='IP')})
    context={
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'form': form
    }
    return render(request, 'equipe/funcionarios_cadastrar.html', context)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def funcionario_editar(request, id):
    funcionario=Funcionario_CEVEST_OS.objects.get(id=id)
    form=Funcionario_Form_editar(instance=funcionario)
    if request.method=='POST':
        form=Funcionario_Form_editar(request.POST, instance=funcionario)
        if form.is_valid():
            form.save()
            return redirect('funcionarios')
    context={
        'titulo': apps.get_app_config('cevest_os').verbose_name,
        'form': form,
        'funcionario': funcionario
    }     
    return render(request, 'equipe/funcionarios_editar.html', context)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def funcionario_deletar(request, id):
    funcionario=Funcionario_CEVEST_OS.objects.get(id=id)
    funcionario.delete()

    return redirect('cevest_os:funcionarios')

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def atribuir_equipe(request, id):
    try:
        instancia=CEVEST_OS_ext.objects.get(os=id)
        form=Equipe_Form(instance=instancia)        
    except Exception as e:
        form=Equipe_Form(initial={'os': id})
        instancia=None
        
    if request.method=='POST':
        if instancia:
            form=Equipe_Form(request.POST, instance=instancia)
        else:
            form=Equipe_Form(request.POST)
        if form.is_valid:
            form.save()
            return redirect('cevest_os:detalhes_os', id)
    context={
            'titulo': apps.get_app_config('cevest_os').verbose_name,   
            'form':form,
        }
    return render(request, 'cevest_os/adicionar_ext.html', context)

@group_required('cevest_os_acesso', 'cevest_os_funcionario')
def pontos_os(request, id):

cevest_os/templates/nav_cevest_os.html
<div id="navegacao" class="container">
    <div class="row">
      <div class="col  d-flex">
        <a href="{% url 'cevest_os:os_painel' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_painel" class="s-nav rounded-circle"></div>
            <p class="text-dark">Painel</p>
          </div>
        </a>  
        <a href="{% url 'cevest_os:os_index' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_index" class="s-nav rounded-circle"></div>
            <p class="text-dark">Serviços</p>
          </div>
        </a>  
        <a href="{% url 'cevest_os:add_os' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_solicitar" class="s-nav rounded-circle "></div>
            <p class="text-dark text-center">Solicitar</p>
          </div>
        </a>
        <a href="{% url 'cevest_almoxarifado:index' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_almoxarifado" class="s-nav rounded-circle"></div>
            <p class="text-dark">Almoxarifado</p>
          </div>
        </a>              
        <a href="{% url 'cevest_os:kpi' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_kpi" class="s-nav rounded-circle "></div>
            <p class="text-dark text-center">Indicadores</p>
          </div>
        </a>                     
        {% if request.user.is_staff %}
        <a href="{% url 'cevest_os:funcionarios' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_funcionarios" class="s-nav rounded-circle"></div>
            <p class="text-dark">Funcionarios</p>
          </div>
        </a> 
        <!-- <a href="{% url 'administrativo' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="admin" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark">DJ-Admin</p>
          </div>
        </a> -->
        {% endif %}
      </div>
    </div>
  </div>
  <style>
    #os_inicio{      
      background-color: white !important;
      background-image: url(/static/images/icones/os_inicio.png);
      background-size: contain;
    }
    #os_solicitar{
      background-color: white !important;
      background-image: url(/static/images/icones/os_solicitar.png);
      background-size: contain;
    }
    #os_kpi{
      background-color: white !important;
      background-image: url(/static/images/icones/os_kpi.png);
      background-size: contain;
    }
    #os_almoxarifado{
      background-color: white !important;
      background-image: url(/static/images/icones/os_almoxarifado.png);
      background-size: contain;
    }
    #os_funcionarios{
      background-color: white !important;
      background-image: url(/static/images/icones/os_funcionarios.png);
      background-size: contain;
    }
    #os_painel{
      background-color: white !important;
      background-image: url(/static/images/icones/os_painel.png);
      background-size: contain;
    }
    #admin{
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_admin.png);
      background-size: contain;
    }
  </style>

cevest_os/templates/os_base.html
{% extends 'os_template.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block head_js %}
{% endblock %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main%}
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block end_js %}
{% endblock %}

cevest_os/templates/os_footer.html
{% load static %}
<footer class="row" style="border-top: 1px solid rgb(184, 184, 184);">        
  <div class="col">
    <div class="row  pt-5 pb-4 mobile-flex-column">
      <div class="col d-flex flex-column">
        <img class="img-fluid logo m-auto" src="{% static '/images/logo.jpg' %}" alt="">
        <p class="mx-auto mt-4">
          <!-- <a class="text-dark" target="_blank" href="https://www.facebook.com/polouerjnovafriburgo/">
            <i class="fa-brands fa-facebook fa-2x me-4 mb-2"></i>
          </a> -->
          <!-- <i class="fa-brands fa-linkedin fa-2x me-4 mb-2"></i> -->
          <!-- <a class="text-dark" target="_blank" href="https://www.instagram.com/polouerjnovafriburgo/">
            <i class="fa-brands fa-instagram fa-2x me-4 mb-2"></i>
          </a> -->
          <!-- <i class="fa-brands fa-youtube fa-2x me-4 mb-2"></i> -->
          <!-- <i class="fa-brands fa-whatsapp fa-2x me-4"></i> -->
          <!-- <i class="fa-brands fa-twitter fa-2x"></i> -->
        </p>
      </div>
      <div class="col">
        <!-- <h5>Sobre Nós</h5> -->
        <p>
          <b class="text-uppercase">
            <!-- Prefeitura Municipal de Nova Friburgo em pareceria com a UERJ -->
          </b>
        </p>
        <p>
          <b><i class="fa-solid fa-location-dot me-2"></i></b> 
          Av. Alberto Braune, 225 - Centro, Nova Friburgo - RJ, 28613-001
        </p>
        <p> 
          <b><i class="fa-solid fa-clock me-2"></i></b>
          08:00 às 17:00 de Seg. à Sex.
        </p>
        <p>
          <b><i class="fa-solid fa-phone me-2"></i></b>
          (22) 2525-9100
        </p>
      </div>
    </div>
    <div class="row bg-black">
      <div class="col d-flex px-4 pt-4 pb-2">
        <div class="d-flex mx-auto">
         <b class="ms-2">© SECRETARIA DE CIÊNCIA, TECNOLOGIA, INOVAÇÃO E EDUCAÇÃO PROFISSIONALIZANTE E SUPERIOR.</b>
        </div>
      </div>          
    </div>
    <div class="row">
      <div class="col text-center pb-3 bg-black">
        <a href="#">
          Política de Privacidade
        </a>
      </div>
    </div>
  </div>
</footer>    

cevest_os/templates/os_header.html
{% load static %} 
{% load bootstrap5 %}
<header class="row">
  <div class="col" style="border-bottom: 1px solid rgb(184, 184, 184);">
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">                                  
            <a class="navbar-brand" href="/">
              
              <img class="img-fluid logo" src="{% static '/images/logo.jpg' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item">                        
                  <a class="nav-link {%block index%}{%endblock%}" href="/">
                    Início
                  </a>
                </li>
                <li class="nav-item">                        
                  <a class="nav-link{% block os %}{%endblock%}" href="{% url 'cevest_os:add_os' %}">
                  Ordem de Serviço
                  </a>
                </li>                     
                {% if request.user.is_staff %}
                <li class="nav-item">                                          
                  <div class="dropdown">
                    <button class="btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                      Administrativo
                    </button>
                    <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end text-start" aria-labelledby="dropdownMenuButton1">                      
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'almoxarifado:index' %}">Almoxarifado</a>
                      </li>  
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'cevest_os:funcionarios' %}">Funcionários</a>
                      </li> 
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'cevest_os:os_index' %}">Ordem de Serviço</a>
                      </li>                                                                  
                    </ul>
                  </div>
                </li>
                {% endif %}               
              </ul>
              <div class="d-flex ms-auto">                                              
                {% if not request.user.is_authenticated %}
                <a href="/admin" class="btn text-uppercase" type="submit"><i class="fa-solid fa-user me-2"></i> Login</a>
                {% else %}
                <div class="dropdown">
                  <button class="btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user-large me-2"></i>
                    {{ request.user.first_name }}
                  </button>
                  <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                    {% if request.user.is_superuser %}
                    <li><a class="dropdown-item py-2 text-center" href="/admin/">Administração</a></li>
                    {% endif %}
                    <!-- <li><a class="dropdown-item py-2 text-center" href="#">Meu perfil</a></li> -->
                    <!-- <li><a class="dropdown-item py-2" href="#">Meu perfil</a></li> -->
                    <li>
                      <a class="dropdown-item text-center py-2" href="/admin/logout">
                        <i class="fa-solid fa-arrow-right-from-bracket me-2"></i></i> Logout                            
                      </a>
                    </li>
                  </ul>
                </div>
                
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
  </div>
</header>