cevest_os/urls.py
from django.urls import path
from . import views
 
app_name='cevest_os'
urlpatterns = [
    # path('', views.index, name='os_index'),
    path('', views.os_index, name='os_index'),
    path('painel/', views.os_painel, name='os_painel'),
    path('os/', views.add_os, name='add_os'),

    path('os/painel/<id>/', views.detalhes_os, name='detalhes_os'),
    path('os/painel/<id>/pontos', views.pontos_os, name='pontos_os'),
    path('imprimir/', views.os_index, name='imprimir_nada'),
    path('imprimir/<ids>/', views.imprimir_varias_os, name='imprimir_varias'),
    path('os/painel/<id>/imprimir/', views.imprimir_os, name='imprimir'),
    path('os/painel/<id>/alterar_status/<opcao>', views.change_status_os, name='change_status_os'),
    path('os/painel/<id>/alterar_prioridade/<opcao>', views.change_prioridade_os, name='change_prioridade_os'),
    path('os/painel/<id>/atender', views.atender_os, name='atender_os'),

    path('os/kpi', views.graficos, name='kpi'),
    path('funcionario', views.funcionarios_listar, name='funcionarios'),
    path('funcionario/cadastrar/', views.funcionario_cadastrar, name='cadastrar funcionario'),
    path('funcionario/editar/<id>/', views.funcionario_editar, name='editar funcionario'),
    path('funcionario/deletar/<id>/', views.funcionario_deletar, name='deletar funcionario'),

    path('os/painel/<id>/equipe/', views.atribuir_equipe, name='atribuir equipe')
]

cursos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
 
app_name='cursos'
urlpatterns = [
    path('', views.index, name='home'),
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('editar-cadastro/', views.editar_cadastro, name='editar_cadastro'),
    path('editar-senha/', views.alterar_senha, name='alterar_senha'),
    path('editar-cadastro-pessoa/', views.editar_cadastro_pessoa, name='editar_cadastro_pessoa'),
    path('atividade/<tipo>', views.cursos, name="cursos"),            
    path('atividade/<tipo>/<filtro>', views.cursos_filtrado, name="filtrar"),            
    path('atividade/<tipo>/<id>/detalhe', views.curso_detalhe, name="curso_detalhe"),            
    path('atividade/<tipo>/<id>/matricular', views.matricular, name="matricula"),            
    # path('prematricula/', views.prematricula, name="prematricula"),
    path('ensino-superior/', views.ensino_superior, name="ensino_superior"),
    path('ensino-tecnico/', views.ensino_tecnico, name="ensino_tecnico"),
    path('curriculo-vitae/', views.curriculo_vitae, name="curriculo_vitae"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),    
    path('', include('cursos.urls')),    
    path('eventos/', include('eventos.urls')),    
    path('almoxarifado/', include('cevest_os.urls')),
    path('almoxarifado/a/', include('cevest_almoxarifado.urls')),    
    path('newsletter/', include('newsletter.urls')),

    path('administracao/', include('administracao.urls')),    
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404

from autenticacao.functions import aluno_required
from .models import *
from .forms import *
from datetime import date, datetime

from .models import *
from .forms import *
from autenticacao.forms import Form_Pessoa
from eventos.models import Evento
from django.apps import apps
from random import shuffle

from django.urls import reverse
def index(request):
    try:
        eventos = Evento.objects.filter(app_name='cursos', is_destaque = True)
    except:
        eventos=[]
    
    cursos = list(Curso.objects.filter(tipo='C', ativo=True).order_by('?')[:8])
    palestras = list(Curso.objects.filter(tipo='P', ativo=True).order_by('?')[:4])
    shuffle(cursos)
    context = { 
        'titulo': apps.get_app_config('cursos').verbose_name,
        'eventos': eventos,
        'cursos': cursos,   
        'cursos_en': Curso_Ensino_Superior.objects.all()[:4],
        'palestras': palestras 
    }

    return render(request, 'cursos/index.html', context)



def cursos(request, tipo):
    form = Aluno_form()
    categorias = Categoria.objects.all()
    cursos = []
    if tipo == 'cursos':        
            cursos=Curso.objects.filter(tipo='C', ativo=True)
    elif tipo == 'palestras':
            cursos=Curso.objects.filter(tipo='P', ativo=True)    

    context = {
        'categorias':categorias,
        'cursos': cursos,
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name,        
        'tipo': tipo
    }
    if tipo == 'cursos':
        return render(request, 'cursos/cursos.html', context)
    elif tipo == 'palestras':  
        return render(request, 'cursos/palestras.html', context)
    raise Http404("Página não encontrada")  

def cursos_filtrado(request, tipo, filtro):
    form = Aluno_form()
    categorias = Categoria.objects.all()
    cursos = []
    if tipo == 'cursos':       
       cursos=Curso.objects.filter(tipo='C', categoria__nome=filtro, ativo=True)
    elif tipo == 'palestras':                
        cursos=Curso.objects.filter(tipo='P', categoria__nome=filtro, ativo=True)

    context = {
        'categorias': categorias,
        'cursos': cursos,
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name,
        'filtro': filtro,
        'tipo': tipo
    }
    if tipo == 'cursos':
        return render(request, 'cursos/cursos.html', context)
    elif tipo == 'palestras':  
        return render(request, 'cursos/palestras.html', context)
    raise Http404("Página não encontrada")

def curso_detalhe(request, tipo, id):    
    curso=Curso.objects.get(id=id)    
    context={
        'curso': curso,
        'tipo': tipo,
        'titulo': apps.get_app_config('cursos').verbose_name,
        'turmas': Turma.objects.filter(curso=curso)
    }
    return render(request, 'cursos/curso_detalhe.html', context)

@login_required
def candidatar(request, id):

    curso = Curso.objects.get(id=id)
    form = Aluno_form(initial={'curso': curso})
    if request.method == 'POST':
        form = Aluno_form(request.POST)
        if form.is_valid():
            form.save()

    context = {
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name,
    }
    return render(request, 'cursos/cadastrar_candidato.html', context)


def prematricula(request):
    form = Aluno_form(prefix="candidato")
    form_responsavel = CadastroResponsavelForm(prefix="responsavel")

    categorias = Categoria.objects.all()
    cursos = []

    for i in categorias:
        cursos.append(
            {'categoria': i, 'curso': Curso.objects.filter(categoria=i, ativo=True)})

    if request.method == 'POST':
        dtnascimento_cp = request.POST.get("candidato-dt_nascimento")
        form = Aluno_form(request.POST, prefix="candidato")
        form_responsavel = CadastroResponsavelForm(
            request.POST, prefix="responsavel")

        try:
            dtnascimento_hr = datetime.strptime(dtnascimento_cp, "%d-%m-%Y")
        except:
            dtnascimento_hr = datetime.strptime(dtnascimento_cp, "%Y-%m-%d")

        dt_nascimento = dtnascimento_hr.date()

        today = date.today()
        age = today.year - dt_nascimento.year - \
            ((today.month, today.day) < (dt_nascimento.month, dt_nascimento.day))
        teste = True
        candidato = False

        try:
            cpf = request.POST['cpf']
            candidato = Aluno.objects.get(cpf=cpf)
        except Exception as e:
            pass

        if candidato:        
            turma = Turma.objects.get(id=i)
            if candidato:
                try:
                    Matricula.objects.get(
                        candidato=candidato, turma__curso=turma.curso)
                    messages.error(
                        request, 'Candidato já matriculado no curso ' + turma.curso.nome)
                    return redirect('cursos:curso_detalhe')
                except:
                    pass

            if (turma.idade_minima is not None and age < turma.idade_minima) or (turma.idade_maxima is not None and age > turma.idade_maxima):
                teste = False

        if form.is_valid() and teste:
            candidato = form.save(commit=False)

            if age < 18:

                if form_responsavel.is_valid():

                    responsavel = form_responsavel.save(commit=False)
                    responsavel.aluno = candidato

                else:
                    return redirect('cursos:curso_detalhe')

                responsavel.save()
                candidato.save()

            else:

                candidato.save()

            for i in request.POST.getlist('turmas'):
                Matricula.objects.create(
                    aluno=candidato, turma=turma, status='c')

            messages.success(
                request, 'Pré-inscrição realizada com sucesso! Aguarde nosso contato para finalizar inscrição.')
            return redirect('/')
        else:
            if not teste:
                messages.error(
                    request, 'Não foi possível realizar a inscrição na turma: A idade não atende a faixa etária da turma.')
                return redirect('/prematricula')

    context = {
        'form': form,
        'form_responsavel': form_responsavel,
        'categorias': cursos,
        'titulo': apps.get_app_config('cursos').verbose_name,
    }
    return render(request, 'cursos/pre_matricula.html', context)

def alterarCad(request):
    return render(request, 'cursos/alterar_cad.html')


def resultado(request):
    return render(request, 'cursos/resultado.html')

@login_required
def matricular(request, tipo, id):
    curso=Curso.objects.get(id=id)
    pessoa=Pessoa.objects.get(user=request.user)

    #checa se já é aluno para por informações no formulario
    try:
        aluno=Aluno.objects.get(pessoa=pessoa)
        form = Aluno_form(prefix="candidato", instance=aluno)
        try:            
            form_responsavel = CadastroResponsavelForm(prefix="responsavel", instance=aluno)
        except:
            pass
    except Exception as E:        
        aluno=None     
        form = Aluno_form(prefix="candidato")    
        form_responsavel = CadastroResponsavelForm(prefix="responsavel")

    # Checa a idade e se precisa de responsavel
    dtnascimento = pessoa.dt_nascimento    
    today = date.today()
    age = today.year - dtnascimento.year - \
            ((today.month, today.day) < (dtnascimento.month, dtnascimento.day))    
    # precisa_responsavel=age<18
    precisa_responsavel=False
    
    if request.method == 'POST':
        
        form = Aluno_form(request.POST, prefix="candidato", instance=aluno)
        if precisa_responsavel:
            form_responsavel = CadastroResponsavelForm(
                request.POST, prefix="responsavel", instance=aluno)

        
        teste = True        
        
        candidato = aluno
        

        #checando idade minima e maxima para o curso
        turmas=Turma.objects.filter(curso=curso)
        pode_cursar=True
        if len(turmas)!=0:
            for turma in turmas:
                if (turma.idade_minima is not None and age < turma.idade_minima) or (turma.idade_maxima is not None and age > turma.idade_maxima):
                    teste = False
                    if not teste:
                        print('entrou aqui')
                        pode_cursar=False
                        teste=True
            
        #validação das informações do forms
        if form.is_valid() and pode_cursar:
            if candidato:
                for turma in turmas:
                    try:
                        Matricula.objects.get(
                            aluno=candidato, turma__curso=turma.curso)
                        messages.error(
                            request, 'Candidato já matriculado no curso: ' + turma.curso.nome)
                        return redirect(reverse('cursos:curso_detalhe', args=[tipo, id]))
                    except Exception as E:                        
                        pass
            candidato = form.save(commit=False)

            if precisa_responsavel:
                if form_responsavel.is_valid():
                    responsavel = form_responsavel.save(commit=False)
                    responsavel.aluno = candidato
                else:       
                    messages.warning(
                    request, 'Preencha corretamente os campos do formulário!')
                    context = {
                        'age': age,
                        'form': form,
                        'form_responsavel': form_responsavel,     
                        'titulo': apps.get_app_config('cursos').verbose_name,
                        'curso': curso,
                        'pessoa': pessoa

cursos/templates/email.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<!--[if gte mso 9]>
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
<![endif]-->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="x-apple-disable-message-reformatting">
  <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge"><!--<![endif]-->
  <title></title>
  
    <style type="text/css">
      @media only screen and (min-width: 520px) {
  .u-row {
    width: 500px !important;
  }
  .u-row .u-col {
    vertical-align: top;
  }

  .u-row .u-col-100 {
    width: 500px !important;
  }

}

@media (max-width: 520px) {
  .u-row-container {
    max-width: 100% !important;
    padding-left: 0px !important;
    padding-right: 0px !important;
  }
  .u-row .u-col {
    min-width: 320px !important;
    max-width: 100% !important;
    display: block !important;
  }
  .u-row {
    width: calc(100% - 40px) !important;
  }
  .u-col {
    width: 100% !important;
  }
  .u-col > div {
    margin: 0 auto;
  }
}
body {
  margin: 0;
  padding: 0;
}

table,
tr,
td {
  vertical-align: top;
  border-collapse: collapse;
}

p {
  margin: 0;
}

.ie-container table,
.mso-container table {
  table-layout: fixed;
}

* {
  line-height: inherit;
}

a[x-apple-data-detectors='true'] {
  color: inherit !important;
  text-decoration: none !important;
}

table, td { color: #000000; } #u_body a { color: #0000ee; text-decoration: underline; }
    </style>
  
  

</head>

<body class="clean-body u_body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #e7e7e7;color: #000000">
  <!--[if IE]><div class="ie-container"><![endif]-->
  <!--[if mso]><div class="mso-container"><![endif]-->
  <table id="u_body" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #e7e7e7;width:100%" cellpadding="0" cellspacing="0">
  <tbody>
  <tr style="vertical-align: top">
    <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top">
    <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="background-color: #e7e7e7;"><![endif]-->
    

<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
    <div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
      <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding: 0px;background-color: transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:500px;"><tr style="background-color: transparent;"><![endif]-->
      
<!--[if (mso)|(IE)]><td align="center" width="500" style="width: 500px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
<div class="u-col u-col-100" style="max-width: 320px;min-width: 500px;display: table-cell;vertical-align: top;">
  <div style="height: 100%;width: 100% !important;">
  <!--[if (!mso)&(!IE)]><!--><div style="height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;"><!--<![endif]-->
  
<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">
        
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td style="padding-right: 0px;padding-left: 0px;" align="center">
      
      <img align="center" border="0" src="images/image-1.png" alt="" title="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 480px;" width="480"/>
      
    </td>
  </tr>
</table>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:8px;font-family:arial,helvetica,sans-serif;" align="left">
        
  <h1 style="margin: 0px; line-height: 140%; text-align: left; word-wrap: break-word; font-weight: normal; font-size: 22px;">
    Olá, {{aluno.nome}}!
  </h1>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:9px;font-family:arial,helvetica,sans-serif;" align="left">
        
  <div>
    <hr>
<p>Você foi aceito(a) para participar da seguinte atividade: {{turma.curso.nome}}</p>

<p>As aulas começarão no dia {{turma.data_inicio}}, {{turma.horario}}, {{turma.local}}</p>


  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:25px 10px 10px;font-family:arial,helvetica,sans-serif;" align="left">
        
  <!--[if mso]><style>.v-button {background: transparent !important;}</style><![endif]-->

{% if turma.grupo_whatsapp%}

<div align="center">
<p style="margin-bottom: 8px">A turma possui um grupo no WhatsApp. O grupo será o canal de comunicação com os inscritos.</p>

  <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="" style="height:37px; v-text-anchor:middle; width:257px;" arcsize="13.5%"  stroke="f" fillcolor="#3AAEE0"><w:anchorlock/><center style="color:#FFFFFF;font-family:arial,helvetica,sans-serif;"><![endif]-->  
    <a href="{{turma.grupo_whatsapp}}" target="_blank" class="v-button" style="box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #3AAEE0; border-radius: 5px;-webkit-border-radius: 5px; -moz-border-radius: 5px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;">
      <span style="display:block;padding:10px;line-height:120%;">Acessar grupo de WhatsApp da turma</span>
    </a>
  <!--[if mso]></center></v:roundrect><![endif]-->
</div>

{% endif %}


      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">
        
  <div style="line-height: 140%; text-align: right; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;">Polo de Extensão da Uerj em Nova Friburgo</p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
  </div>
</div>
<!--[if (mso)|(IE)]></td><![endif]-->
      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
    </div>
  </div>
</div>


    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->
    </td>
  </tr>
  </tbody>
  </table>
  <!--[if mso]></div><![endif]-->
  <!--[if IE]></div><![endif]-->
</body>

</html>

cursos/templates/header_.html
{% load static %}
<script>
  function hide_node(element){
    element.style.display = 'none'
  }
</script>

<header class="row">
  <div class="col" style="border-bottom: 1px solid rgb(255, 255, 255);">
    <div class="row" id="nav-superior">
      <div class="col d-flex text-light">
        <div class="logo-nf nv-sp">
          <img src="{% static 'images/brasao-nf.png' %}" class="img-fluid ms-2">
        </div>
        <p class="my-auto ms-3">PREFEITURA DE NOVA FRIBURGO</p>
        <div class="my-auto mx-auto">
          <ul class="d-flex">
            <li class="me-1"><a href="">Capacitação </a>|</li>
            <li class="me-1"> <a href=""> Cidade Inteligente </a>|</li>
            <li class="me-1"> <a href=""> Eventos </a>|</li>
            <li> <a href=""> Finanças</a></li>
          </ul>
        </div>
        <div class="nv-login ms-auto">
          {% if not request.user.is_authenticated %}
          <a href="{% url 'login' %}" class="btn text-uppercase text-light" type="submit"><i
              class="fa-regular fa-user me-2"></i> Login</a>
          {% else %}
          <div class="dropdown">
            <button class="btn text-light " type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown"
              aria-expanded="false">
              <i class="fa-solid fa-user-large me-2"></i>
              {{ request.user.first_name }}
            </button>
            <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
              {% if request.user.is_superuser %}
              <li><a class="dropdown-item py-2 text-center" href="/admin/">Administração</a></li>
              {% endif %}
              <li>
                <a class="dropdown-item text-center py-2" href="{% url 'admin:logout' %}">
                  <i class="fa-solid fa-arrow-right-from-bracket me-2"></i></i> Logout
                </a>
              </li>
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="row" id="nav-inferior">
      <div class="col d-flex">
        <div class="img-logo">
          <img src="{% static 'images/logo_desenvolvenf.png' %}" class="img-fluid">
        </div>
        <div class="nv-titulo my-auto ms-3">
          <h2>| {{titulo}}</h2>
        </div>
        <div class="nv-social ms-auto d-flex">
          <div class="d-flex my-auto me-3">
            <i class="fa-solid fa-magnifying-glass"></i>
          </div>
          <div class="d-flex my-auto">
            <div class="d-social d-flex mx-2"><a href="" class="a-social m-auto"><i
                  class="fa-brands fa-instagram"></i></a></div>
            <div class="d-social d-flex"><a href="" class="a-social m-auto"><i class="fa-brands fa-facebook-f"></i></a>
            </div>
            <div class="d-social d-flex mx-2"><a href="" class="a-social m-auto"><i
                  class="fa-brands fa-twitter"></i></a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

{% for message in messages %}
  <div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible d-flex justify-content-between" role="alert" >
      {{ message }}

      <button type="button" class="btn-close" onClick="hide_node(this.parentNode.parentNode)" data-dismiss="alert" aria-label="Close">
      </button>
    </div>
  </div>
{% endfor %}

<section class="row pt-4">
  <div class="row">
    <div class="col  d-flex justify-content-center">
      <a class="d-flex flex-column" href="/">
        <div class="s-nav rounded-circle mx-4 d-flex">
        <img style="height: 35px;" class="img-fluid m-auto" src="/static/images/icons/home.png" alt="">
      </div>
      <span class="mx-auto mt-1 text-dark">Home</span>
    </a>
    <a class="d-flex flex-column" href="{% url 'cursos' %}">
        <div class="s-nav rounded-circle d-flex pt-2">
            <img style="height: 50px;" class="img-fluid m-auto" src="/static/images/icons/cursos2.png" alt="">
        </div>
        <span class="mx-auto mt-1 text-dark">Cursos</span>
    </a>
      <a class="d-flex flex-column" href="{% url 'prematricula' %}">
        <div class="s-nav rounded-circle mx-4 d-flex">
        <img style="height: 50px;" class="img-fluid m-auto" src="/static/images/icons/palestras.png" alt="">
      </div>
      <span class="mx-auto mt-1 text-dark">Palestras</span>
    </a>
      {% if request.user.is_staff %}
      <a class="d-flex flex-column" href="{% url 'administrativo' %}"><div class="s-nav rounded-circle d-flex">
        <img style="height: 60px;" class="img-fluid m-auto" src="/static/images/icons/admin.png" alt="">
      </div>
      <span class="mx-auto mt-1 text-dark">Admin</span>
    </a>
      {% endif %}
      {% if request.user.is_staff %}
      <a class="d-flex flex-column" href="/admin"><div class="s-nav rounded-circle mx-4 d-flex pt-1 pe-1">
        <img style="height: 40px;" class="img-fluid m-auto" src="/static/images/icons/django.svg" alt="">
        </div>
        <span class="mx-auto mt-1 text-dark">Django-Admin</span>
    </a>
      {% endif %}
    </div>
  </div>
</section>

cursos/templates/nav_cursos.html
<div id="navegacao" class="container">
  <div class="row links-nav-container">
    <div class="col links-nav">
      <a href="{% url 'cursos:home' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-index" class="s-nav rounded-circle {% block index %}{% endblock %}"></div>
          <p class="text-dark">Início</p>
        </div>
      </a>
      <a href="{% url 'cursos:cursos' tipo='cursos' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-cursos" class="s-nav rounded-circle"></div>
          <p class="text-dark text-center">Cursos</p>
        </div>
      </a>

      <a href="{% url 'cursos:cursos' tipo='palestras' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-palestras" class="s-nav rounded-circle"></div>
          <p class="text-dark">Palestras</p>
        </div>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{% url 'cursos:area_do_estudante' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-estudante" class="s-nav rounded-circle"></div>
          <p class="text-dark text-center">Área do<br>estudante</p>
        </div>
      </a>
      {% endif %}
      <a href="https://casadotrabalhador.pmnf.rj.gov.br/" class="ms-auto">
        <div class="d-flex flex-column align-items-center">
          <div id="s-vaga" class="s-nav rounded-circle"></div>
          <p class="text-dark text-center">Casa do<br/>Trabalhador</p>
        </div>
      </a>
      {% if request.user.is_staff %}
      <a href="{% url 'cevest_os:os_index' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-servicos" class="s-nav rounded-circle"></div>
          <p class="text-dark">Almoxarifado</p>
        </div>
      </a>  
      <a href="{% url 'administrativo2' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-admin" class="s-nav rounded-circle destaque"></div>
          <p class="text-dark">Admin</p>
        </div>
      </a>
      {% endif %}
    </div>
  </div>
</div>
<style>
  @media(max-width: 950px){
    .ms-auto{
      margin-left: 0px !important;
    }
  }
</style>