cursos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
 
app_name='cursos'
urlpatterns = [
    path('', views.index, name='home'),
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('editar-cadastro/', views.editar_cadastro, name='editar_cadastro'),
    path('editar-senha/', views.alterar_senha, name='alterar_senha'),
    path('editar-cadastro-pessoa/', views.editar_cadastro_pessoa, name='editar_cadastro_pessoa'),
    path('atividade/<tipo>', views.cursos, name="cursos"),            
    path('atividade/<tipo>/<filtro>', views.cursos_filtrado, name="filtrar"),            
    path('atividade/<tipo>/<id>/detalhe', views.curso_detalhe, name="curso_detalhe"),            
    path('atividade/<tipo>/<id>/matricular', views.matricular, name="matricula"),            
    # path('prematricula/', views.prematricula, name="prematricula"),
    path('ensino-superior/', views.ensino_superior, name="ensino_superior"),
    path('ensino-tecnico/', views.ensino_tecnico, name="ensino_tecnico"),
    path('curriculo-vitae/', views.curriculo_vitae, name="curriculo_vitae"),
]

eventos/urls.py
from django.urls import path
from . import views

app_name='eventos' 
urlpatterns = [
    path('', views.index, name="index"),
    path('evento/<id>', views.evento_detalhe, name="detalhe"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),    
    path('', include('cursos.urls')),    
    path('eventos/', include('eventos.urls')),    
    path('almoxarifado/', include('cevest_os.urls')),
    path('almoxarifado/a/', include('cevest_almoxarifado.urls')),    
    path('newsletter/', include('newsletter.urls')),

    path('administracao/', include('administracao.urls')),    
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/models.py
from django.db import models

# Create your models here.

class Evento(models.Model):
    DIAS_SEMANA_CHOICES = (
        ('1', 'Domingo'),
        ('2', 'Segunda-Feira'),
        ('3', 'Terça-Feira'),
        ('4', 'Quarta-Feira'),
        ('5', 'Quinta-Feira'),
        ('6', 'Sexta-Feira'),
        ('7', 'Sábado'),
    )

    titulo = models.CharField(max_length=64)
    subtitulo = models.CharField(max_length=64)
    app_name = models.CharField(max_length=164)
    descricao = models.TextField()
    data_inicio = models.DateField()
    data_fim = models.DateField()

    local = models.CharField(max_length=128)
    google_maps = models.URLField()
    idade_minima = models.IntegerField(
        verbose_name='Idade mínima', null=True, blank=True)
    idade_maxima = models.IntegerField(
        verbose_name='Idade máxima', null=True, blank=True)
    banner_img = models.ImageField(upload_to='banner_evento', verbose_name='Arte do evento')
    is_destaque = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s' % (self.titulo, self.subtitulo)

eventos/forms.py
from .models import *
from django import forms


class Evento_form(forms.ModelForm):
    class Meta:
        model = Evento
        widgets={
            'app_name': forms.HiddenInput()
        }
        exclude = []

    banner_img = forms.FileField(required=False, label='Imagem do banner', widget=forms.FileInput(
        attrs={'class': 'form-control','accept': 'application/image', 'enctype': "multipart/form-data"}))

eventos/views.py
from django.shortcuts import render
from django.apps import apps
from .models import Evento
from desenvolve_nf.models import Carousel_Index

def index(request):
    context={
        'titulo': apps.get_app_config('eventos').verbose_name,
        'eventos': Evento.objects.filter(is_destaque=True).order_by('data_inicio'),
        'carousel': Carousel_Index.objects.filter(ativa=True)
    }
    return render(request, "evento.html", context)

def evento_detalhe(request, id):
    evento=Evento.objects.get(id=id)
    context={
        'evento': evento,
        'titulo': apps.get_app_config('eventos').verbose_name,
        'categoria': apps.get_app_config(evento.app_name).verbose_name,
        'eventos': Evento.objects.filter(is_destaque=True),
        'carousel': Carousel_Index.objects.filter(ativa=True)
    }
    return render(request, "evento_detalhe.html", context)

eventos/templates/evento.html
{% extends 'template.html' %} {% load static %} {% block nav %}
<link rel="stylesheet" href="/static/css/owl.carousel.min.css" />
<link rel="stylesheet" href="/static/css/carousel_desenvolve.css" />
<link rel="stylesheet" href="/static/css/eventos.css" />
<style>
  .item {
    box-shadow: none !important;
    background-color: none !important;
  }
</style>
<!-- <div id="main-carousel" class="row">
  <div class="col px-0 pt-5 mt-5">
    <div class="owl-carousel">
      {% for item in carousel %}
      <div class="item w-100">
        {% if item.url %}<a href="{{item.url}}"
          >{% endif %}
          <img
            src="{{item.image.url}}"
            class="d-block w-100"
            alt="{{item.nome}}"
          />
          {% if item.url %}</a
        >{% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div> -->
<!-- <script
  src="https://code.jquery.com/jquery-3.6.3.min.js"
  integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
  crossorigin="anonymous"
></script>
<script src="/static/js/owl.carousel.min.js"></script>
<script>
  $(".owl-carousel").owlCarousel({
    center: true,
    items: 2,
    loop: true,
    margin: 10,
    autoWidth: true,
    autoplay: true,
    nav: true,
    responsive: {
      0: {
        items: 1,
      },
      600: {
        items: 3,
      },
      1000: {
        items: 5,
      },
    },
  });
</script> -->
{% endblock %} {% block css %}
<link rel="stylesheet" href="/static/css/index.css" />
<link rel="stylesheet" href="/static/css/carrossel.css" />
<script src="/static/js/carrossel.js"></script>
<style>
  .item {
    box-shadow: 0px 10px 15px -3px rgba(0, 0, 0, 0.341);
    background-color: #ffffff00;
  }
</style>

{% endblock %} {% block main %}
<div class="container pt-5">
  <div class="row mx-auto mt-5 bg-destaque ps-4 pb-2 pt-1">
    <!-- <div class="row">
    <h2 class="ms-4 py-1">Destaque</h2>
  </div>
  <div class="row ">
    <div class="d-flex bg-white img-txt">
      <div class="img-destaque">
        <img src="{% static 'images/animais.jpg' %}" class="img-fluid">
      </div>
      <div class="text-destaque pt-4 pb-0 px-4 d-flex flex-column" style="max-width: 450px;">
        <h5 class="mb-1">Bem-Estar Animal Nova Friburgo</h5>
        <p class="local"><a href="{{evento_destaque.google_maps}}"><i class="fa-solid fa-location-dot mb-3 me-2"></i>ARP - Nova Friburgo - Rio de Janeiro.</a></p>    
        <p class="time mb-4 text-center">03/02/2023 - 28/02/2023 - 17:00 - 21:00</p>        
        <h7 class="mb-1">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, deleniti reprehenderit. Et similique impedit esse.
        </h7>
        
        <p class="inf text-secondary mt-2">Com transmissão online</p>
        <button class="btn btn-outline-primary btn-details me-auto" id="esp">Detalhes</button>
      </div>
    </div>
  </div> -->
    <div class="row">
      <!-- <h2 class="ms-2 py-1">Destaque</h2> -->
    </div>
    <div class="row">
      <div class="col pb-3">
        <div
          class="d-flex evento_teste"
          style="font-size: 25pt; font-weight: 600"
        >
          <h1>Todos os eventos</h1>
          <!-- <div class="dropdown ms-auto">
            <a
              class="ps-2"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              style="text-decoration: none; color: black; font-size: 18pt"
            >
              Todos
              <span style="font-size: 15pt">
                <i class="ps-2 fa-solid fa-chevron-down"></i>
              </span>
            </a>
            <ul
              class="dropdown-menu dropend"
              aria-labelledby="dropdownMenuButton1"
            >
              <li>
                <a class="dropdown-item" href="#"
                  ><i class="fa-solid fa-filter me-2"></i>CECIERJ</a
                >
              </li>
              <li>
                <a class="dropdown-item" href="#"
                  ><i class="fa-solid fa-filter me-2"></i>UERJ</a
                >
              </li>
              <li>
                <a class="dropdown-item" href="#"
                  ><i class="fa-solid fa-filter me-2"></i>CEFET</a
                >
              </li>
            </ul>
          </div> -->
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col d-flex flex-wrap evento_teste2">
        {% for evento in eventos %}
        <div
          class="banner_destaque d-flex flex-column flex-xl-column bg-white img-txt"
          style="width: 35vw; margin: auto; box-shadow: 0px 10px 15px -3px rgba(0, 0, 0, 0.1);"
        >
          <div class="img-destaque" style="width: 100%">
            <img class="img-fluid" src="{{evento.banner_img.url}}" />
          </div>
          <div class="text-destaque pt-4 pb-0 px-4 d-flex flex-column">
            <h5 class="mb-1">{{evento.titulo}}</h5>
            <h6 style="color: gray;">
              {{evento.data_inicio|date:'d/m/y'}}{% if evento.data_fim %} -
              {{evento.data_fim|date:'d/m/y'}}{% endif %}
            </h6>
            <h6 class="mb-1" style="font-weight: 400">{{evento.subtitulo}}</h6>
            
            <p class="local mt-3">
              <a href="{{evento.google_maps}}"
                ><i class="fa-solid fa-location-dot mb-3 me-2"></i
                >{{evento.local}}</a
              >
            </p>            
            <!-- <p class="inf text-secondary mt-2">Com transmissão online</p> -->
            <a href="{% url 'eventos:detalhe' evento.id %}"
              class="mt-2 w-100 btn btn-outline-primary btn-details me-auto"
              id="esp"
            >
              Detalhes
          </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <style>
    .item {
      padding-top: 15px;
    }
  </style>

  <div class="row mx-auto px-5" style="height: 100px">
    <script>
      document.getElementById("index").classList.add("s-nav-active");
    </script>
  </div>
</div>
{% endblock %} {% block footer %}
<section id="newsletter" class="pb-5" style="background-color: #fff">
  <div class="row border-top">
    <div class="col d-flex d-flex px-5 pt-5">
      <div class="mx-auto d-flex">
        <img
          src="/static/images/blue-envelope.jpg"
          style="width: 100px; transform: rotate(-0.265rad)"
          alt=""
        />
        <span
          class="display-5 my-auto ms-4"
          style="font-family: 'Inter', sans-serif"
          >Receba nossas novidades!</span
        >
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex pt-3">
      <div class="m-auto d-flex flex-column">
        <p class="text-center">
          Fique por dentro dos nossos principais assuntos, basta socilitar
          abaixo esse serviço!
        </p>
        <button class="mx-auto btn btn-primary mt-4 px-5">Solicitar</button>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eventos/templates/evento_detalhe.html
{% extends 'template.html' %}
{% load bootstrap5 %}
{% load static%}
{% block css %}
<script src="{% static 'js/cursos.js' %}"></script>
{% endblock %}
{% block main %}
<div class="row">
    <div class="col d-flex py-5"> 
        <div class="row w-100 mt-3 pt-5">
            <div class="col-10 pb-4 m-auto bg-white px-5" style="border-radius: 30px;">                                
                <div class="row">
                    <div class="col d-flex flex-column">
                        <div class="row">
                            <div class="col d-flex py-4">                                
                                <h1 class="my-auto">
                                    {{evento.titulo}}
                                </h1>   
                                <a href="{% url 'eventos:index' %}" class="btn btn-primary ms-auto my-auto">Voltar</a>
                            </div>
                        </div>
                        <img class="w-100 mx-auto" src="{{evento.banner_img.url}}" alt="" style="border-radius: 30px;">
                    </div>
                </div>   
                <div class="row">
                    <div class="col p-5 d-flex flex-column">
                        <h2>{{evento.subtitulo}}</h2>
                        <b>Origem</b>
                        <p>{{categoria}}</p>
                        <b>Descrição:</b>
                        <p>{{evento.descricao}}</p>                           
                                                                                           
                                                                       
                    </div>
                    <div class="col-5 p-5 d-flex justify-content-between">
                        <div class="row w-100">
                           <div class="col d-flex flex-column">
                            <p class="">
                                <b>
                                  <i class="fa-solid fa-calendar me-3"></i>Data:
                                </b> 
                                
                            </p>    
                            <p class="mb-4 text-center mt-2">{{evento.data_inicio}}{% if data_fim %} até {{data_fim}}{% endif %}</p>
                            <p><b><i class="fa-solid fa-location-dot me-3"></i> Local:</b></p>                                                                                    
                            <p class="mb-4 text-center mt-2"><a href="{{evento.google_maps}}">{{evento.local}}</a></p>
                            {% if evento.idade_minima %}
                            <p><b><i class="fa-solid fa-child-reaching me-3"></i>Faixa Etária</b></p>
                            <p class="mb-4 text-center mt-2">   
                              {% if evento.idade_maxima %}                            
                              {{evento.idade_minima}} anos até {{evento.idade_maxima}} anos
                              {% else %}
                              {{evento.idade_minima}}+
                              {% endif %}                              
                            </p> 
                            {% else %}
                              {% if evento.idade_maxima %}                              
                              <p><b><i class="fa-solid fa-child-reaching me-3"></i>Faixa Etária</b></p>
                              <p class="mb-4 text-center mt-2">                              
                                até {{evento.idade_maxima}} anos
                              </p> 
                              {% endif %}
                            {% endif %}
                           </div>   
                        </div>
                        
                        
                        
                    </div>
                </div>                  
           
            </div>
        </div>
    </div>
</div>
{% if messages %}              
<!-- MODAL -->
<div class="modal fade" id="resposta" aria-hidden="true" aria-labelledby="respostaLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        {% for message in messages %}
        <div class="modal-header {% if message.tags %}{{message.tags}}{% endif %} border-0">
          <h5 class="modal-title text-dark text-center" id="exampleModalToggleLabel"></h5>
          <button type="button" onclick="myModal.hide();" class="btn-close"></button>
        </div>
        <div class="modal-body px-5 {% if message.tags %}{{message.tags}}{% endif %}">   
           
          <p class="px-4 py-3 text-center">
            {{ message|escape }}
          </p>
          
          
        </div>
        <div class="modal-footer {% if message.tags %}{{message.tags}}{% endif %} border-0">
          
        </div>
        {% endfor %}
      </div>

    </div>
  </div>   
  <script>
   var myModal = new bootstrap.Modal(document.getElementById('resposta'))
   myModal.toggle()
  </script>
  <style>
    .error{
      background-color: rgb(238, 171, 171);
      color: darkred;
      font-weight: 600;
    }
    .success{
      background-color: rgb(182, 238, 171);
      color: rgb(0, 139, 19);
      font-weight: 600
    }
    .warning{
      background-color: rgb(238, 226, 171);
      color: rgb(139, 107, 0);
      font-weight: 600
    }
  </style>
{% endif %} 
{% endblock %}