bemestaranimal/urls.py
from django.urls import path
from . import views

app_name='bemestaranimal'
urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/completar', views.cadastro_tutor, name='completar_cadastro'),
    path('area-tutor/', views.area_tutor, name='area_tutor'),

    #animal
    path('animal/cadastrar', views.cadastrar_animal, name='cadastrar_animal'),
    path('animal/editar/<id>', views.editar_animal, name='editar_animal'),
    path('animal/deletar/<id>', views.deletar_animal, name='deletar_animal'),
    path('animal/cadastrar-errante', views.cadastrar_errante, name='cadastrar_errante'),
        
    path('tutores/', views.listar_tutor, name='listar_tutor'),
    path('tutor/<tutor_id>/animais/', views.listar_animal_tutor, name='listar_animais_tutor'),
    path('tutor/<tutor_id>/animais/<animal_id>', views.cad_infos_extras, name='cadastrar_info'),
    
      #catalogo
    path('catalogo/', views.catalogo, name='catalogo'),
    # path('catalogo/cadastrar', views.cad_catalogo_animal, name='cadastrar_catalogo'),
    path('catalogo/<id>/entrevista-previa', views.entrevistaAdocao, name='entrevista_adocao'),
    
    path('adm/gerar-token', views.gerarToken, name='gerar_token'),
    
    #token
    path('resgatar-cupom', views.resgatar_cupom, name='resgatar_cupom'),
    # path('adm/descontar-token', views.descontarToken, name='descontar_token'),     
]

cursos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
 
app_name='cursos'
urlpatterns = [
    path('', views.index, name='home'),
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('editar-cadastro/', views.editar_cadastro, name='editar_cadastro'),
    path('editar-senha/', views.alterar_senha, name='alterar_senha'),
    path('editar-cadastro-pessoa/', views.editar_cadastro_pessoa, name='editar_cadastro_pessoa'),
    path('atividade/<tipo>', views.cursos, name="cursos"),            
    path('atividade/<tipo>/<filtro>', views.cursos_filtrado, name="filtrar"),            
    path('atividade/<tipo>/<id>/detalhe', views.curso_detalhe, name="curso_detalhe"),            
    path('atividade/<tipo>/<id>/matricular', views.matricular, name="matricula"),            
    # path('prematricula/', views.prematricula, name="prematricula"),
    path('ensino-superior/', views.ensino_superior, name="ensino_superior"),
    path('ensino-tecnico/', views.ensino_tecnico, name="ensino_tecnico"),
    path('curriculo-vitae/', views.curriculo_vitae, name="curriculo_vitae"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),    
    path('', include('cursos.urls')),    
    path('eventos/', include('eventos.urls')),    
    path('almoxarifado/', include('cevest_os.urls')),
    path('almoxarifado/a/', include('cevest_almoxarifado.urls')),    
    path('newsletter/', include('newsletter.urls')),

    path('administracao/', include('administracao.urls')),    
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bemestaranimal/forms.py
import unicodedata
from django import forms
from django.forms import ModelForm, ModelChoiceField
from .models import *
from autenticacao.functions import validate_cpf

class Form_Tutor(ModelForm):
    class Meta:
        model = Tutor
        widgets = {
            'pessoa':forms.HiddenInput(),
        }
        fields = ['tipo_de_moradia', 'pessoa']

class Form_Tipo(ModelForm):
    class Meta:
        model = Tipo
        fields = ['nome']


class Form_Especie(ModelForm):
    class Meta:
        model = Especie
        fields = ['nome_especie']
        
    def clean_nome_especie(self):
        name = self.cleaned_data.get('nome_especie')
        if name:
            name = name.lower()
            name = unicodedata.normalize('NFKD', name).encode('ASCII', 'ignore').decode()
        return name


class Form_Animal(ModelForm):    

    class Meta:
        model = Animal
        
        exclude = ['dt_inclusao', 'especie']
        widgets = {
                'tutor': forms.HiddenInput(), 
                'tipo': forms.RadioSelect()}
        
class Form_Catalogo(ModelForm):
    class Meta:
        model= Catalogo
        fields = ['animal', 'pelagem', 'vacinado']
        widgets = {
            'animal':forms.HiddenInput(),
            'castrado': forms.CheckboxInput(attrs={'role':'switch', 'id':'flexSwitchCheckDefault'}),
            'vacinado': forms.CheckboxInput()
        }

class Form_Errante(ModelForm):

    class Meta:
        model = Errante
        exclude = ['dt_inclusao', 'especie']
        widgets = {
            'tipo':forms.RadioSelect(),
        }

class Form_Info_Extras(ModelForm):
    class Meta:
        model = Informacoes_Extras
        fields = ['alimentacao_tipo', 'alimentacao_periodo', 'condicoes', 'dt_vacinacao', 'dt_vermifugacao', 'complemento', 'dt_registro', 'animal']
        widgets = {
            'alimentacao_periodo':forms.CheckboxSelectMultiple(),
            'dt_vacinacao':forms.TextInput(attrs={'type':'date'}),
            'dt_vermifugacao':forms.TextInput(attrs={'type':'date'}),
            'dt_registro':forms.TextInput(attrs={'type':'date'}),
            'animal':forms.HiddenInput()
        }


class Form_EntrevistaPrevia(ModelForm):
    class Meta:
        model = EntrevistaPrevia
        exclude = []
        widgets = {
            'animal':forms.HiddenInput(),
            'cpf':forms.TextInput(attrs={'onkeydown':'mascara(this,icpf)'}),
            'telefone':forms.TextInput(attrs={'onkeydown':'mascara(this, itel)'}),
            'quest_dois':forms.RadioSelect(),
            'quest_tres':forms.RadioSelect(),
            'quest_quatro':forms.RadioSelect(),
            'quest_cinco':forms.RadioSelect(),
            'quest_seis':forms.RadioSelect(),
            'quest_sete':forms.RadioSelect(),
            'quest_oito':forms.RadioSelect(),
            'quest_nove':forms.RadioSelect(),
            'quest_dez':forms.RadioSelect(),
        }
    def clean_cpf(self):
        cpf = validate_cpf(self.cleaned_data["cpf"])
        return cpf

    def clean_telefone(self):
        telefone = self.cleaned_data["telefone"]
        telefone = telefone.replace('(', '')
        telefone = telefone.replace(' ', '')
        telefone = telefone.replace(')', '')
        telefone = telefone.replace('-', '')
        return telefone

bemestaranimal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.db.models import Count
from .models import *
from .forms import *
from .functions import generateToken
from django.apps import apps
from eventos.models import Evento

def cadastro_tutor(request):
    if request.user.is_authenticated:
        try:
            pessoa = Pessoa.objects.get(user_id=request.user.id)
            if pessoa:
                pass
        except:
            return redirect('bemestaranimal:cadastrar_usuario')
        try:
            tutor = Tutor.objects.get(pessoa_id=pessoa.id)
            verify = True
        except:
            verify = False

        if not verify:
            print(pessoa)
            form_tutor = Form_Tutor(initial={'pessoa':pessoa})
        else:
            return redirect('index')
    else:
        return redirect('autenticacao:cadastrar_usuario')
    if request.method == "POST":
        form_tutor = Form_Tutor(request.POST)
        if form_tutor.is_valid():
            form_tutor.save()
            return redirect('bemestaranimal:index')
    context={
        'form_tutor':form_tutor,
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
    }
    return render(request, 'autenticacao/completar-cadastro.html', context)

def index(request):
    catalogo = Catalogo.objects.all()[:4]
    context = {
        'catalogo':catalogo,
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'eventos': Evento.objects.filter(app_name='bemestaranimal')
    }
    return render(request, 'index.html', context)


@login_required
def area_tutor(request):
    try:
        pessoa = Pessoa.objects.get(user_id=request.user.id)
        tutor = Tutor.objects.get(pessoa_id=pessoa.id)
    except:
        messages.error(request, 'Você não é cadastrado como tutor!')
        return redirect('bemestaranimal:completar_cadastro')
    context={
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
    }
    return render(request, 'tutor/area_tutor.html', context)



@login_required
def cadastrar_animal(request):
    pessoa = Pessoa.objects.get(user_id=request.user.id)
    tutor = Tutor.objects.get(pessoa_id=pessoa.id)
    animal_form = Form_Animal(initial={'tutor':tutor})
    especie_form = Form_Especie()
    if request.method == "POST":
        animal_form = Form_Animal(request.POST, request.FILES)
        especie_form = Form_Especie(request.POST)
        if animal_form.is_valid() and especie_form.is_valid():
            animal = animal_form.save(commit=False)
            v_especie = especie_form.save(commit=False)
            especie, verify = Especie.objects.get_or_create(nome_especie=v_especie.nome_especie)
            animal.especie_id = especie.id
            animal.save()
            animal_form = Form_Animal(initial={'tutor':tutor})
            especie_form = Form_Especie()

    try:
        animais = Animal.objects.filter(tutor=tutor)
    except:
        animais = []
    context = {
        'animal_form': animal_form,
        'especie_form': especie_form,
        'animais':animais,
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
    }
    return render(request, 'tutor/animal_cadastro.html', context)

@login_required
def listar_animal(request):
    pessoa = Pessoa.objects.get(user_id=request.user.id)
    tutor = Tutor.objects.get(pessoa_id=pessoa.id)
    try:
        animais = Animal.objects.filter(tutor=tutor)
    except:
        animais = []
    if len(animais)==0:
        messages.error(request, 'Você não há animais cadastrados ainda.')
        return render(request, 'tutor/area_tutor.html')
    context = {
        'animais':animais,
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
    }
    return render(request, 'tutor/animal_listar.html', context)


@login_required
def editar_animal(request, id):
    animal = Animal.objects.get(id=id)
    especie = Especie.objects.get(id=animal.especie_id)
    animal_form = Form_Animal(instance=animal)
    especie_form = Form_Especie(instance=especie)
    if request.method == "POST":
        especie_form = Form_Especie(request.POST, instance=especie)
        animal_form = Form_Animal(request.POST, instance=animal)
        if animal_form.is_valid() and especie_form.is_valid():
            animal_form.save(commit=False)
            try:
                Animal.objects.get(especie_id=especie.id)
                one = True
            except:
                one = False
            v_especie = especie_form.save(commit=False)
            especie, verify = Especie.objects.get_or_create(nome_especie=v_especie.nome_especie)
            animal.especie = especie
            animal.save()
            if one and request.POST['nome_especie'] != especie.nome_especie:
                try:
                    especie.delete()
                except:
                    pass
        return redirect('cadastrar_animal')               
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'animal':animal,
        'animal_form': animal_form,
        'especie_form': especie_form,
    }
    return render(request, 'tutor/animal_editar.html', context)

@login_required
def deletar_animal(request, id):
    animal = Animal.objects.get(pk=id)
    animal.delete()
    return redirect('cadastrar_animal')

def catalogo(request):
    catalogo = Catalogo.objects.all()
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'catalogo':catalogo
    }
    return render(request, 'catalogo/animal-catalogo.html', context)


def entrevistaAdocao(request, id):
    animal = Catalogo.objects.get(pk=id)
    try:
        pessoa=Pessoa.objects.get(user=request.user)
        entrevistaPrevia_Form = Form_EntrevistaPrevia(initial={
            'animal':animal,
            'nome': pessoa.nome,
            'cpf': pessoa.cpf,
            'telefone': pessoa.telefone,
            'bairro': pessoa.bairro,
            'endereco': pessoa.endereco
            })
    except:
        pessoa=None
        entrevistaPrevia_Form = Form_EntrevistaPrevia(initial={'animal':animal})
    
    if request.method == "POST":
        entrevistaPrevia_Form = Form_EntrevistaPrevia(request.POST)
        if entrevistaPrevia_Form.is_valid():
            entrevistaPrevia_Form.save()
            messages.success(request, 'Uma orientação')
            return redirect('index')
    context = {
        'entrevistaPrevia_Form': entrevistaPrevia_Form,
        'adocao':animal,
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
    }
    return render(request, 'catalogo/entrevista.html', context)
    

@login_required
def resgatar_cupom(request):
    pessoa = Pessoa.objects.get(user_id=request.user.id)
    tutor = Tutor.objects.get(pessoa_id=pessoa.id)
    try:
        cupom = TokenDesconto.objects.get(tutor=tutor)
    except:
        messages.error(request, 'Cupom não disponibilizado.')
        return render(request, 'tutor/area_tutor.html')
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'cupom':cupom
    }
    return render(request, 'tutor/resgatar-token.html', context)


@staff_member_required
def cadastrar_errante(request):
    errante_form = Form_Errante()
    especie_form = Form_Especie()

    context = {
        'errante_form': errante_form,
        'especie_form': especie_form
    }
    if request.method == "POST":
        errante_form = Form_Errante(request.POST, request.FILES)
        especie_form = Form_Especie(request.POST)
        if errante_form.is_valid():
            if especie_form.is_valid():
                errante = errante_form.save(commit=False)
                v_especie = especie_form.save(commit=False)
                especie, verify = Especie.objects.get_or_create(nome_especie=v_especie.nome_especie)
                errante.especie = especie
                errante.save()
                messages.success(request, 'Animal cadastrado com sucesso!')
                return redirect('cadastrar_errante')
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'errante_form': errante_form,
        'especie_form': especie_form
    }
    return render(request, 'errante/animal-errante-cadastro.html', context)

@staff_member_required
def listar_errante(request):
    errantes = Errante.objects.all()
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'errantes':errantes
    }
    return render(request, 'errante/animal_errante.html', context)

@staff_member_required
def listar_tutor(request):
    qntd = Tutor.objects.all().count()
    tutores = Tutor.objects.annotate(num=Count('animal'))
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'tutores':tutores,
        'qntd':qntd,
    }
    return render(request, 'adm/listar-tutores.html', context)

@staff_member_required
def listar_animal_tutor(request, tutor_id):
    animais = Animal.objects.filter(tutor__pessoa__user=tutor_id)
    tutor = Tutor.objects.get(pessoa__user=tutor_id).pessoa.nome
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,
        'animais':animais,
        'tutor':tutor
    }
    return render(request, 'adm/listar-animais-tutor.html', context)


@staff_member_required
def cad_infos_extras(request, tutor_id, animal_id):
    animal = Animal.objects.get(pk=animal_id)
    try:
        info = Informacoes_Extras.objects.get(animal=animal.id)
        if info:
            info_extras_form = Form_Info_Extras(instance=info)
    except:
        info_extras_form = Form_Info_Extras(initial={'animal':Animal.objects.get(pk=animal_id).id})
    context = {
        'titulo': apps.get_app_config('bemestaranimal').verbose_name,

bemestaranimal/templates/footer copy.html
<footer class="row" style="border-top: 1px solid rgb(184, 184, 184);">        
    <div class="col">
      <div class="row  pt-5 pb-4 mobile-flex-column">
        <div class="col d-flex flex-column">
          <img class="img-fluid logo m-auto" src="./static/images/logo_pmnf.png" alt="">
          <p class="mx-auto mt-4">
            <a class="text-dark" target="_blank" href="https://www.facebook.com/polouerjnovafriburgo/">
              <i class="fa-brands fa-facebook fa-2x me-4 mb-2"></i>
            </a>                
            <a class="text-dark" target="_blank" href="https://www.instagram.com/polouerjnovafriburgo/">
              <i class="fa-brands fa-instagram fa-2x me-4 mb-2"></i>
            </a>
          </p>
        </div>
        <div class="col">
          <p>
            <b class="text-uppercase">
              <!-- Prefeitura Municipal de Nova Friburgo em pareceria com a UERJ -->
            </b>
          </p>
          <p>
            <b><i class="fa-solid fa-location-pin me-2"></i></b> 
            Av. Alberto Braune, 225 - Centro, Nova Friburgo - RJ, 28613-001
          </p>
          <p> 
            <b><i class="fa-solid fa-clock me-2"></i></b>
            08:00 às 17:00 de Seg. à Sex.
          </p>
          <p>
            <b><i class="fa-solid fa-phone me-2"></i></b>
            (22) 2525-9100
          </p>
        </div>
      </div>
      <div class="row bg-black">
        <div class="col d-flex px-4 pt-4 pb-2">
          <div class="d-flex mx-auto">
           <b class="ms-2">© SECRETARIA DE CIÊNCIA, TECNOLOGIA, INOVAÇÃO E EDUCAÇÃO PROFISSIONALIZANTE E SUPERIOR.</b>
          </div>
        </div>          
      </div>
      <div class="row">
        <div class="col text-center pb-3 bg-black">
          <a href="#">
            Política de Privacidade
          </a>
        </div>
      </div>
    </div>
</footer> 

bemestaranimal/templates/header copy.html
<header class="row">
    <div class="col" style="border-bottom: 1px solid rgb(255, 255, 255);">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">                                  
              <a class="navbar-brand" href="/">
                
                <img class="img-fluid logo" src="/static/images/logo_pmnf.png" alt="">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                 
                  <li class="nav-item">                        
                    <a class="nav-link" href="/">                      
                        <h1>{{titulo}}</h1>
                    </a>
                  </li>
                  
                </ul>
              </div>
              {% if not request.user.is_authenticated %}
              <a href="{% url 'login' %}" class="btn text-uppercase" type="submit"><i class="fa-solid fa-user me-2"></i> Login</a>
              {% else %}
              <div class="dropdown">
                <button class="btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa-solid fa-user-large me-2"></i>
                  {{ request.user.first_name }}
                </button>
                <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                  {% if request.user.is_superuser %}
                  <li><a class="dropdown-item py-2 text-center" href="/admin/">Administração</a></li>
                  {% endif %}
                  <!-- <li><a class="dropdown-item py-2 text-center" href="#">Meu perfil</a></li> -->
                  <!-- <li><a class="dropdown-item py-2" href="#">Meu perfil</a></li> -->
                  <li>
                    <a class="dropdown-item text-center py-2" href="{% url 'logout' %}">
                      <i class="fa-solid fa-arrow-right-from-bracket me-2"></i></i> Logout                            
                    </a>
                  </li>
                </ul>
              </div>
              {% endif %}
            </div>
              </div>
            </div>
          </nav>
    </div>
</header>

bemestaranimal/templates/header.html
{% load static %}

bemestaranimal/templates/index.html
{% extends 'template.html' %}
{% load static %}
{% block nav %}
{% include 'nav_bemestaranimal.html' %}
{% endblock %}
{% block css %}
<link rel="stylesheet" href="/static/css/index.css">
<link rel="stylesheet" href="/static/css/carrossel.css">
<script src="/static/js/carrossel.js"></script>
{% endblock %}
{% block main %}
<div class="container">
<div class="row mx-auto bg-destaque ps-4 pb-2 pt-1">
  <div class="container">
    <div class="row mx-auto ps-4 pb-5 pt-1">
      <div class="row">
        <h2 class="ms-2 py-1">Destaque</h2>
      </div>
      {% include 'slide.html' %}
    </div>      

      <!-- <div class="row">
    <h2 class="ms-4 py-1">Destaque</h2>
  </div> -->
  <!-- <div class="row ">
    <div class="d-flex bg-white img-txt">
      <div class="img-destaque">
        <img src="{% static 'images/animais.jpg' %}" class="img-fluid">
      </div>
      <div class="text-destaque pt-4 pb-0 px-4 d-flex flex-column" style="max-width: 450px;">
        <h5 class="mb-1">Bem-Estar Animal Nova Friburgo</h5>
        <p class="local"><a href="{{evento_destaque.google_maps}}"><i class="fa-solid fa-location-dot mb-3 me-2"></i>ARP - Nova Friburgo - Rio de Janeiro.</a></p>    
        <p class="time mb-4 text-center">03/02/2023 - 28/02/2023 - 17:00 - 21:00</p>        
        <h7 class="mb-1">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, deleniti reprehenderit. Et similique impedit esse.
        </h7>
        
        <p class="inf text-secondary mt-2">Com transmissão online</p>
        <button class="btn btn-outline-primary btn-details me-auto" id="esp">Detalhes</button>
      </div>
    </div>
  </div> -->
</div>
<div class="row">
  <h2 class="ms-5 pt-5 pb-4">Adote um Amigo!</h2>
</div>
<style>
  .item{
  padding-top: 15px;
}

</style>
<div class="row mx-auto px-5">
  <div class="d-flex justify-content-evenly carosel">
    {% for adocao in catalogo %}
    <div class="item carosel-item">
      <div class="c-img px-3">
        <img src="{{adocao.animal.animal_image.url}}" class="img-fluid rounded-circle">
      </div>
      <div class="c-text mx-2 d-flex flex-column py-1 px-4 pt-3">
        <h5>{% if adocao.animal.nome %}{{adocao.animal.nome}}{% endif %}</h5>
        <p class="time text-secondary">{% if adocao.animal.raca %}{{adocao.animal.raca}} - {% endif %}{{adocao.animal.idade}} {% if adocao.animal.idade == 1 %}ano.{% else %}anos.{% endif %}</p>        
        <a href="{% url 'bemestaranimal:entrevista_adocao' adocao.id %}" class="btn btn-outline-primary rounded-1 btn-details py-1  my-3 mx-auto" id="esp-2">Ver detalhes</a>
      </div>
    </div>
    {% endfor %}
    
  </div>
</div>
<div class="row mx-auto px-5" style="height: 100px;">
  <script>
    document.getElementById('index').classList.add('s-nav-active');
  </script>
</div>
</div>
</div>
{% endblock %}

bemestaranimal/templates/message.html
{% if messages %}              
            <script src="http://polouerj.novafriburgo.rj.gov.br/js/modal.js"></script>
            <!-- MODAL -->
            <div class="modal fade" id="resposta" aria-hidden="true" aria-labelledby="respostaLabel" tabindex="-1">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                  <div class="modal-content">
                    {% for message in messages %}
                    <div class="modal-header {% if message.tags %}{{message.tags}}{% endif %} border-0">
                      <h5 class="modal-title text-dark text-center" id="exampleModalToggleLabel"></h5>
                      <button type="button" onclick="myModal.hide();" class="btn-close"></button>
                    </div>
                    <div class="modal-body px-5 {% if message.tags %}{{message.tags}}{% endif %}">   
                       
                      <p class="px-4 py-3 text-center">
                        {{ message|escape }}
                      </p>
                      
                      
                    </div>
                    <div class="modal-footer {% if message.tags %}{{message.tags}}{% endif %} border-0">
                      
                    </div>
                    {% endfor %}
                  </div>
            
                </div>
              </div>   
              <script>
               var myModal = new bootstrap.Modal(document.getElementById('resposta'))
               myModal.toggle()
              </script>
              <style>
                .error{
                  background-color: rgb(238, 171, 171);
                  color: darkred;
                  font-weight: 600;
                }
                .success{
                  background-color: rgb(182, 238, 171);
                  color: rgb(0, 139, 19);
                  font-weight: 600
                }
                .warning{
                  background-color: rgb(238, 226, 171);
                  color: rgb(139, 107, 0);
                  font-weight: 600
                }
              </style>
{% endif %}

bemestaranimal/templates/nav_bemestaranimal.html
<div id="navegacao" class="container">
    <div class="row">
      <div class="col  d-flex">
        <a href="{% url 'bemestaranimal:index' %}"  class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="index" class="s-nav rounded-circle "></div>
            <p class="text-dark">Início</p>
          </div>
        </a>
        <a href="{% url 'bemestaranimal:area_tutor' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="tutor" class="s-nav rounded-circle "></div>
            <p class="text-dark text-center">Área do Tutor</p>
          </div>
        </a>
        <a href="{% url 'bemestaranimal:catalogo' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="adote" class="s-nav rounded-circle"></div>
            <p class="text-dark">Adoção</p>
          </div>
        </a>
        {% if user_belongs_to_group or request.user.is_superuser%}
        <a href="{% url 'descontar_token' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="loja" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark">Loja</p>
          </div>
        </a>
        {% endif %}
        {% if request.user.is_staff %}
        <a href="{% url 'administrativo' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="admin" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark">Admin</p>
          </div>
        </a>
        {% endif %}
      </div>
    </div>
  </div>
  <style>
    #index{      
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_inicio.png);
      background-size: contain;
    }
    #tutor{
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_tutor.png);
      background-size: contain;
    }
    #adote{
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_adote.png);
      background-size: contain;
    }
    #loja{
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_loja.png);
      background-size: contain;
    }
    #admin{
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_admin.png);
      background-size: contain;
    }
  </style>